Resources:
  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.projectsTableName}
      AttributeDefinitions:
        - AttributeName: projectId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: projectId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1